/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */

/**
 * Mapping of chainId to EncryptedDiceGame contract address
 */
export const encryptedDiceGameAddresses: Record<number, `0x${string}`> = {
  // Localhost/Hardhat Network
  31337: "0xb87016578Ad00e7bAAF1d9D99296df7d215A62b2",

  // Sepolia Testnet
  11155111: "0x3160Fd44b86Ec234d773b6426cC10B7B6C7daD6d",

  // Ethereum Mainnet (for future use)
  1: "0x0000000000000000000000000000000000000000",
} as const;

export function getEncryptedDiceGameAddress(
  chainId: number,
): `0x${string}` | undefined {
  return encryptedDiceGameAddresses[chainId];
}
