/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */

import { type Chain } from "viem";

export type EncryptedDiceGameInfo = {
  address: `0x${string}`;
  abi: typeof import("./EncryptedDiceGameABI").EncryptedDiceGameABI;
};

type EncryptedDiceGameAddressMap = {
  [key: number]: EncryptedDiceGameInfo;
};

export const encryptedDiceGameAddresses: EncryptedDiceGameAddressMap = {
  // Localhost/Hardhat Network
  31337: {
    address: "0xb87016578Ad00e7bAAF1d9D99296df7d215A62b2" as `0x${string}`,
    abi: require("./EncryptedDiceGameABI").EncryptedDiceGameABI,
  },

  // Sepolia Testnet
  11155111: {
    address: "0x3160Fd44b86Ec234d773b6426cC10B7B6C7daD6d" as `0x${string}`,
    abi: require("./EncryptedDiceGameABI").EncryptedDiceGameABI,
  },

  // Ethereum Mainnet (for future use)
  1: {
    address: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    abi: require("./EncryptedDiceGameABI").EncryptedDiceGameABI,
  },
} as const;

export function getEncryptedDiceGameInfo(
  chainId: number,
): EncryptedDiceGameInfo | undefined {
  return encryptedDiceGameAddresses[chainId];
}

export function getEncryptedDiceGameAddress(
  chainId: number,
): `0x${string}` | undefined {
  return encryptedDiceGameAddresses[chainId]?.address;
}
